packages:
  - lib
  - examples/*

catalog:
  '@types/react': ^19.2.0
  '@types/react-dom': ^19.2.0
  "@vitejs/plugin-react": ^5.1.1
  react: ^19.2.0
  react-dom: ^19.2.0
  typescript: ^5.9.3
  vite: ^7.2.2
