packages:
  - lib
  - examples/*

catalog:
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3
  "@vitejs/plugin-react": ^5.1.2
  react: ^19.2.1
  react-dom: ^19.2.1
  typescript: ^5.9.3
  vite: ^7.2.7
