packages:
  - lib
  - packages/*

autoInstallPeers: false

catalog:
  '@types/react': ^19.2.17
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^6.0.4
  jsdom: ^29.1.1
  react: ^19.2.7
  react-dom: ^19.2.7
  rimraf: ^6.1.3
  typescript: ^7.0.2
  vite: ^8.1.5
  vitest: ^4.1.10

# Security Settings
#  Increase security by only allowing updates that are at least 24 hours old
minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
#  Prevent updates to packages that have exotic dependencies (e.g. git dependencies, file dependencies, etc.)
blockExoticSubdeps: true
#  Prevent updates to packages if its trust level has decreased compared to previous releases
# trustPolicy: "no-downgrade"
