packages:
  - lib
  - examples/*

catalog:
  "@types/react": ^19.2.10
  "@types/react-dom": ^19.2.3
  "@vitejs/plugin-react": ^5.1.2
  react: ^19.2.4
  react-dom: ^19.2.4
  typescript: ^5.9.3
  vite: ^7.3.1
