packages:
  - lib
  - examples/*

catalog:
  "@types/react": "^19.1.9"
  "@types/react-dom": "^19.1.7"
  "@vitejs/plugin-react": "^5.0.0"
  "react": "^19.1.1"
  "react-dom": "^19.1.1"
  "typescript": "^5.9.2"
  "vite": "^7.0.6"
