packages:
  - lib
  - examples/*

catalog:
  "@types/react": "^19.1.9"
  "@types/react-dom": "^19.1.6"
  "@vitejs/plugin-react": "^4.7.0"
  "react": "^19.1.1"
  "react-dom": "^19.1.0"
  "typescript": "^5.8.3"
  "vite": "^7.0.6"
