packages:
  - lib
  - examples/*

catalog:
  "@types/react": "^19.1.12"
  "@types/react-dom": "^19.1.8"
  "@vitejs/plugin-react": "^5.0.2"
  "react": "^19.1.1"
  "react-dom": "^19.1.1"
  "typescript": "^5.9.2"
  "vite": "^7.1.4"
