packages:
  - lib
  - examples/*

catalog:
  '@types/react': ^19.1.0
  '@types/react-dom': ^19.1.0
  '@vitejs/plugin-react': ^5.0.4
  react: ^19.1.0
  react-dom: ^19.1.0
  typescript: ^5.9.3
  vite: ^7.1.9
