packages:
  - lib
  - examples/*

catalog:
  "@types/react": "^19.1.3"
  "@types/react-dom": "^19.1.4"
  "@vitejs/plugin-react": "^4.4.1"
  "react": "^19.1.0"
  "react-dom": "^19.1.0"
  "typescript": "^5.8.3"
  "vite": "^6.3.3"
