name: Build & Test

on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Test

    strategy:
      matrix:
        node_version: [lts/-1, lts/*, latest]
        package:
          - "@forward-software/react-auth"
          - "@forward-software/react-auth-google"
          - "@forward-software/react-auth-apple"
      fail-fast: false

    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8

      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node_version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Install peerDependencies
        run: pnpm install --no-frozen-lockfile --config.auto-install-peers=true

      - name: Test package
        run: pnpm --config.auto-install-peers=true --filter "${{ matrix.package }}" test

  build:
    name: Build

    strategy:
      matrix:
        package:
          - "@forward-software/react-auth"
          - "@forward-software/react-auth-google"
          - "@forward-software/react-auth-apple"
      fail-fast: false

    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8

      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
          cache: pnpm

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Install peerDependencies
        run: pnpm install --no-frozen-lockfile --config.auto-install-peers=true

      - name: Build package
        run: pnpm --config.auto-install-peers=true --filter "${{ matrix.package }}" build
